# Generated by Django 5.2.6 on 2025-09-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffProfile',
            new_name='StaffRole',
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='staff.staffrole'),
        ),
    ]
