# Generated by Django 5.2.6 on 2025-09-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_staffprofile_staffrole_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='hired_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
