# Generated by Django 5.2.4 on 2025-09-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='hired_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter'), ('CLEANER', 'Cleaner'), ('CASHIER', 'Cashier')], default='WAITER', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='staff',
        ),
    ]
