# Generated by Django 5.2.4 on 2025-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_line_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='ORD123456', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
