# Generated by Django 5.2.4 on 2025-09-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_payment_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
